### ISSUE TITLE
Recent published artifact was built with Java8

### ISSUE THREAD

**Issue by lambyqq** [LiveRamp/cascading_ext#68]
I'm currently using MultiBuffer in my cascading jobs and I noticed my job starting to fail today, after a new artifact of cascading_ext/1.6-SNAPSHOT was published yesterday:

Exception in thread "main" java.lang.UnsupportedClassVersionError: com/liveramp/cascading_ext/multi_group_by/MultiBuffer : Unsupported major.minor version 52.0

I'm wondering if we can revert the artifact since Hadoop doesn't well support Java8.

Thanks!

**Comment by bpodgursky** [comment]
@lambyqq Hadoop should reliably work with java 8 now: https://issues.apache.org/jira/browse/HADOOP-11090.  We are using it in production.

@TV4Fun would you be able to do a release build of cascading_ext at the last JDK 1.7 commit?

**Comment by lambyqq** [comment]
@bpodgursky Thanks Ben for your prompt reply!
Unfortunately it's going to take quite a long time at my company to upgrade Hadoop version... So I'll really appreciate if you guys could release a build of cascading_ext with JDK1.7 (maybe tag it with some version).  Thanks!

**Comment by bpodgursky** [comment]
We're working on doing that now.

**Comment by lambyqq** [comment]
Thanks a lot Ben and Joel!
